identifier: ldpcz35ci7n147y0
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: my-blog
homeFolder: C:\Users\a2z\Documents\angular-projects\my-blog
distFolder: dist/my-blog
outDir: C:\Users\a2z\Documents\angular-projects\my-blog\dist\static
handle404: ''
allowErrorCollect: false
